apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-deployment
  labels:
    app: book-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: book-app
  template:
    metadata:
      labels:
        app: book-app
    spec:
      containers:
        - name: book-app
          image: albertflorinus/book-app:latest
          ports:
            - containerPort: 5000
          envFrom:
            - configMapRef:
                name: app-config
