apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-deployment
  labels:
    app: book-auth
spec:
  replicas: 2
  selector:
    matchLabels:
      app: book-auth
  template:
    metadata:
      labels:
        app: book-auth
    spec:
      containers:
        - name: book-auth
          image: albertflorinus/book-auth:latest
          ports:
            - containerPort: 4000
          envFrom:
            - configMapRef:
                name: app-config
