apiVersion: v1
kind: Service
metadata:
  name: auth-service
  labels:
    app: book-auth
spec:
  selector:
    app: book-auth
  ports:
    - protocol: TCP
      port: 4000
      targetPort: 4000
  type: ClusterIP
