apiVersion: v1
kind: Service
metadata:
  name: db-service
spec:
  selector:
    app: book-db
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432
      nodePort: 30544
  type: NodePort